FROM clojure
RUN apt-get update -y && \
      apt-get install -y git \
      sqlite
# RUN git clone https://github.com/liquidz/vim-iced /tmp/vim-iced
# ADD iced /tmp/vim-iced/bin/
# RUN chmod +x /tmp/vim-iced/bin/iced
# ENV PATH="/tmp/vim-iced/bin:$PATH"
# RUN echo "$PATH"
COPY . /src/app
WORKDIR /src/app
RUN clj -A:dev -P
EXPOSE 12345 
EXPOSE 3000
ENTRYPOINT ["clj", "-M:dev:repl-server"]
