FROM clojure
RUN apt-get update -y && \
      apt-get install -y git \
      sqlite
COPY . /src/app
WORKDIR /src/app
RUN clj -A:dev -P
EXPOSE 12345 
EXPOSE 3000
ENTRYPOINT ["clj", "-M:dev:repl-server"]
