apiVersion: v1
kind: Service
metadata:
  labels:
    app: diabetes-dashboard
  name: diabetes-dashboard-server
  namespace: diabetes-dashboard
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: server
  selector:
    app: diabetes-dashboard-server
  type: ClusterIP
